### ISSUE TITLE
We sometimes get "Overloaded" error for chat completion calls (succeeds on retry)

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/anthropic-provider#1]
We sometimes get "Overloaded" error for chat completion calls (succeeds on retry) when running gptscript using anthropic models:

```
INFO:     127.0.0.1:60444 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_utils.py", line 87, in collapse_excgroups
  |     yield
  |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 190, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    |     raise exc
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    |     with collapse_excgroups():
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/python/61f9ec42638d80e92436bdc09bd76431bb84bbdcb603d817fb25fd3775f3e52a/python/lib/python3.12/contextlib.py", line 158, in __exit__
    |     self.gen.throw(value)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    |     raise exc
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/74eee4a74267f82d7cb405a347ddb097dad0297d/python3.12/main.py", line 15, in log_body
    |     return await call_next(request)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    |     raise app_exc
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    |     await route.handle(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    |     await self.app(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    |     raise exc
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/74eee4a74267f82d7cb405a347ddb097dad0297d/python3.12/main.py", line 117, in completions
    |     accumulated = await stream.get_final_message()
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 237, in get_final_message
    |     await self.until_done()
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 262, in until_done
    |     await consume_async_iterator(self)
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_utils/_streams.py", line 11, in consume_async_iterator
    |     async for _ in iterator:
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_streaming.py", line 144, in __aiter__
    |     async for item in self._iterator:
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 322, in __stream__
    |     async for event in super().__stream__():
    |   File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_streaming.py", line 191, in __stream__
    |     raise self._client._make_status_error(
    | anthropic.APIStatusError: {'type': 'error', 'error': {'type': 'overloaded_error', 'message': 'Overloaded'}}
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/python/61f9ec42638d80e92436bdc09bd76431bb84bbdcb603d817fb25fd3775f3e52a/python/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/74eee4a74267f82d7cb405a347ddb097dad0297d/python3.12/main.py", line 15, in log_body
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/74eee4a74267f82d7cb405a347ddb097dad0297d/python3.12/main.py", line 117, in completions
    accumulated = await stream.get_final_message()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 237, in get_final_message
    await self.until_done()
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 262, in until_done
    await consume_async_iterator(self)
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_utils/_streams.py", line 11, in consume_async_iterator
    async for _ in iterator:
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_streaming.py", line 144, in __aiter__
    async for item in self._iterator:
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/lib/streaming/_messages.py", line 322, in __stream__
    async for event in super().__stream__():
  File "/Users/sangeethahariharan/Library/Caches/gptscript/repos/runtimes/venv/0de1d54a75a02c5bc3e6b07d35e6bf1eaba8173ac8d19b8f274d2995d017bf0e/lib/python3.12/site-packages/anthropic/_streaming.py", line 191, in __stream__
    raise self._client._make_status_error(
anthropic.APIStatusError: {'type': 'error', 'error': {'type': 'overloaded_error', 'message': 'Overloaded'}}
2024/03/28 15:47:30 error, status code: 500, message: invalid character 'I' looking for beginning of value
```

**Comment by drpebcak** [comment]
Closing this - 'overloaded' means the anthropic platform was receiving too many requests.. nothing we can do about that in the provider.
